[project]
name = "tt"
description = "Keep a log of activities"
authors = [{name = "Noah Everett", email = "noahe@metrized.com" }]
requires-python = ">=3.11"
dynamic = ["version"]
dependencies = ["click", "requests"]

[project.optional-dependencies]
dev = ["ruff", "pytest",  "black", "mypy"]

[project.scripts]
"tt" = "tt:cli"

[tool.setuptools.dynamic]
version = { attr = "tt.__version__" }

[tool.ruff.lint]
ignore = ["E731"]

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"
